import SearchBox from "@/components/searchbox";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Penultimate Guitar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="m-auto w-fit">Penultimate Guitar</h1>
        <SearchBox />
      </main>
    </>
  );
}
